# Generated by Django 3.2.9 on 2022-10-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0002_auto_20221016_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='menuItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemname', to='webApi.menuitem'),
        ),
    ]
