# Generated by Django 3.2.9 on 2022-10-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0003_auto_20221016_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='menuItem',
        ),
        migrations.AddField(
            model_name='item',
            name='menuItemId',
            field=models.CharField(default='', max_length=20),
        ),
    ]
