# Generated by Django 3.2.9 on 2022-10-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0004_auto_20221016_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='menuItemId',
        ),
        migrations.AddField(
            model_name='item',
            name='menuItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='itemname', to='webApi.menuitem'),
            preserve_default=False,
        ),
    ]
