# Generated by Django 3.2.9 on 2022-01-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('contact_comments', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('sub_category', models.CharField(max_length=50)),
                ('extra_comments', models.TextField()),
                ('userId', models.IntegerField()),
                ('userName', models.CharField(max_length=15)),
            ],
        ),
    ]
