# Generated by Django 3.2.9 on 2022-01-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='images/'),
        ),
    ]
