# Generated by Django 3.2.9 on 2022-02-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_productdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
