# Generated by Django 3.2.9 on 2022-02-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_productdetail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='timeStamp',
            field=models.CharField(default='', max_length=50),
        ),
    ]
