# Generated by Django 3.2.9 on 2022-03-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productdetail_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Donate/images/'),
        ),
    ]
