# Generated by Django 3.2.9 on 2022-06-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_productdetail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intiatorId', models.CharField(max_length=30)),
                ('friendId', models.CharField(max_length=30)),
                ('friendName', models.CharField(max_length=200)),
                ('lastMessage', models.TextField(blank=True)),
                ('timeStampMessage', models.CharField(max_length=300)),
                ('timeStampChat', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='contact_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='extra_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='Donate/images/'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='timeStamp',
            field=models.CharField(max_length=50),
        ),
    ]
