# Generated by Django 3.2.9 on 2022-07-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220625_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=30)),
                ('token', models.TextField()),
                ('timestamp', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mychats',
            name='initiatorName',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
