# Generated by Django 3.2.9 on 2022-07-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220711_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(max_length=30)),
                ('sub_category', models.CharField(blank=True, max_length=50)),
                ('timeStamp', models.CharField(max_length=50)),
                ('userId', models.IntegerField()),
                ('userName', models.CharField(max_length=15)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='mychats',
            name='initiatorName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
