# Generated by Django 3.2.9 on 2022-07-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220725_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mychats',
            name='initiatorName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='requestedproductdetail',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='requestedproductdetail',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='requestedproductdetail',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
