# Generated by Django 3.2.9 on 2024-03-25 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20220725_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mychats',
            old_name='intiatorId',
            new_name='initiatorId',
        ),
        migrations.RemoveField(
            model_name='fcmtokens',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='requestedproductdetail',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='requestedproductdetail',
            name='userName',
        ),
        migrations.AddField(
            model_name='fcmtokens',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestedproductdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
