# Generated by Django 3.2.9 on 2024-03-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20240325_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='timeStamp',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='requestedproductdetail',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='requestedproductdetail',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='requestedproductdetail',
            name='timeStamp',
            field=models.DateTimeField(),
        ),
    ]
