# Generated by Django 3.2.9 on 2024-03-30 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_productdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requestedproductdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestedproductdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
