# Generated by Django 3.2.9 on 2024-04-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_deleteaccountrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtokens',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
