# Generated by Django 3.2.9 on 2024-05-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_fcmtokens_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mychats',
            name='chat_room_id',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mychats',
            name='sender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
