# Generated by Django 3.2.9 on 2025-02-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20240507_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeleteAccountRequest',
        ),
    ]
