# Generated by Django 3.2.9 on 2025-05-19 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0023_delete_deleteaccountrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_product_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
