# Generated by Django 3.2.9 on 2025-05-29 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0024_alter_productdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtokens',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fcmtokens',
            name='token',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='fcmtokens',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to='auth.user'),
            preserve_default=False,
        ),
    ]
