# Generated by Django 3.2.9 on 2025-05-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20250529_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtokens',
            name='token',
            field=models.TextField(),
        ),
    ]
